# -*- coding: utf-8 -*-
"""
Styles centralisés Leafy Life.
Transposition des variables de css/global.css en constantes Python.
"""

# ---- Navbar ----
COLOR_NAVBAR_BG = "#131313"
COLOR_NAVBAR_BORDER = "#1e1e1e"
COLOR_NAVBAR_LINK_BG = "#f8f3ec"
COLOR_NAVBAR_LINK_HOVER_BG = "#3a3a3a"
COLOR_NAVBAR_LINK_ACTIVE_BG = "#1e1e1e"
COLOR_NAVBAR_LINK_TEXT = "#131313"

# ---- Search bar ----
COLOR_SEARCH_BAR_BG = "#f8f3ec"
COLOR_SEARCH_BAR_BORDER = "#7e7e7e"
COLOR_SEARCH_BAR_TEXT = "#000000"
COLOR_SEARCH_BAR_PLACEHOLDER_TEXT = "#555555"

# ---- Leafs écran ----
COLOR_LEAFS_BG = "#f0f8ff"
COLOR_LEAFS_TITLE_BORDER = "#145d36"
COLOR_LEAFS_TITLE_BG = "#27b7ff"
COLOR_LEAF_BUTTON_BG = "#ffffff"
COLOR_LEAF_BUTTON_BORDER = "#145d36"
COLOR_LEAF_BUTTON_HOVER_BG = "#e0f0ff"
COLOR_LEAF_BUTTON_ACTIVE_BG = "#a0c1f5"
COLOR_LEAF_BUTTON_IMG_BG = "#d0e4f8"
COLOR_LEAF_BUTTON_NAME = "#000000"
COLOR_LEAF_BUTTON_RARITY = "#a0a0a0"
COLOR_LVL_BADGE_BG = "#e8f4f8"
COLOR_LVL_BADGE_BORDER = "#0066cc"
COLOR_LVL_BADGE_TEXT = "#0066cc"

# ---- O2 / CO2 / Stock ----
COLOR_O2_BG = "#4da6ff"
COLOR_O2_BORDER = "#006bb3"
COLOR_CO2_BG = "#6ecf7a"
COLOR_CO2_BORDER = "#2e8b39"
COLOR_STOCK_BG = "#ffd700"
COLOR_STOCK_BORDER = "#bfa500"

# ---- Shop (pour écrans futurs) ----
COLOR_SHOP_BG = "#e7b7e7"
COLOR_SHOP_TITLE_BG = "#b86ab8"
COLOR_SHOP_TITLE_BORDER = "#7e3e7e"

# ---- Inventory (pour écrans futurs) ----
COLOR_INVENTORY_BG = "#005bb8"
COLOR_INVENTORY_TITLE_BG = "#27b7ff"
COLOR_INVENTORY_TITLE_BORDER = "#145d36"

# ---- Modal ----
COLOR_MODAL_BG = "#1ea25e"
COLOR_MODAL_BORDER = "#145d36"
COLOR_MODAL_OVERLAY_BG = "rgba(0,0,0,0.6)"
COLOR_MODAL_ACTION_CONFIRM_BG = "#28b238"
COLOR_MODAL_ACTION_CONFIRM_BORDER = "#1e661f"
COLOR_MODAL_ACTION_CANCEL_BG = "#a94442"
COLOR_MODAL_ACTION_CANCEL_BORDER = "#6e2c2c"
COLOR_MODAL_CLOSE_BG = "#e0e0e0"
COLOR_MODAL_CLOSE_TEXT = "#999999"

# ---- Formes (border-radius) ----
BORDER_RADIUS_DEFAULT = 8
BORDER_RADIUS_MEDIUM = 12
BORDER_RADIUS_LARGE = 16
BORDER_RADIUS_SMALL = 4
