# —————————————————————————————————————————————————————————
# —————————————————————— Style Leafs ——————————————————————
# —————————————————————————————————————————————————————————
    # ------------------- Style général -------------------
LEAF_BG_COLOR = "#1a1a1a"
LEAF_TITLE_COLOR = "#1ABD35"
LEAF_SHEARCHBAR_BG_COLOR = "#212121"
LEAF_SHEARCHBAR_INPUT_COLOR = "#FFFFFF"
LEAF_SHEARCHBAR_LABEL_COLOR = "#276E31"
LEAF_SHEARCHBAR_HINT_COLOR = "#276E31"
LEAF_SHEARCHBAR_BORDER_COLOR = "#131313"
LEAF_SHEARCHBAR_COLOR_FOCUSED = "#575757"
LEAF_SHEARCHBAR_BORDER_COLOR_FOCUSED = "#2b2b2b"
    # ------------------- Style des boutons ---------------
LEAF_BUTTON_BG_COLOR = "#8db15e"
LEAF_BUTTON_BORDER_COLOR = "#607F37"
LEAF_BUTTON_BG_COLOR_HOVER = "#a7bd8b"
LEAF_BUTTON_BG_COLOR_CLICKED = "#63853c"
LEAF_BUTTON_IMG_BG_COLOR = "#6f8b4a"
LEAF_BUTTON_IMG_BORDER_COLOR = "#59842a"
LEAF_BUTTON_NAME_COLOR = "#ffffff"
LEAF_BUTTON_TYPE_COLOR = "#45691f"
LEAF_BUTTON_BIOME_COLOR = "#59842a"
    # ------------------- Style des cartes ----------------
LEAF_CARD_SHADOW_COLOR = (0.6, '#000000')
LEAF_CARD_BG_COLOR = "#1a1a1a"
LEAF_CARD_BORDER_COLOR = "#555555"
LEAF_CARD_TITLE_TEXT_COLOR = "#ffffff"
LEAF_CARD_INFO_TEXT_COLOR = "gray"
LEAF_CARD_BADGE_BG_COLOR = "#2a2a3e"
LEAF_CARD_BADGE_BG_HOVER_COLOR = "#40405c"
LEAF_CARD_BADGE_BORDER_COLOR = "#131313"
LEAF_CARD_PROGRESS_BAR_BG_COLOR = "#4E4E4E"
LEAF_CARD_PROGRESS_BAR_HP_COLOR = "#92b368"
LEAF_CARD_PROGRESS_BAR_NUTRIENTS_COLOR = "#f2c14e"
LEAF_CARD_PROGRESS_BAR_NUTRIENTS_ALERT_COLOR = "#ef540c"
LEAF_CARD_PROGRESS_BAR_HYDRATION_COLOR = "#4b86b4"
LEAF_CARD_PROGRESS_BAR_HYDRATION_ALERT_COLOR = "#ff0000"
LEAF_CARD_PROGRESS_BAR_ATK_COLOR = "purple"
LEAF_CARD_PROGRESS_BAR_LVL_COLOR = "#4b0fffc5"

# —————————————————————————————————————————————————————————
# ————————————————————— Style Shop ————————————————————————
# —————————————————————————————————————————————————————————
    # ------------------- Style général -------------------
SHOP_BG_COLOR = "#292929"
SHOP_TITLE_COLOR = "white"
SHOP_TITLE_COLOR_ITINERANT = "#B68B31C5"
SHOP_TITLE_BG_COLOR = "#7a3a7a"
SHOP_TITLE_BORDER_COLOR = "#5a1a5a"
SHOP_SHEARCHBAR_BG_COLOR = "#393939"
SHOP_SHEARCHBAR_INPUT_COLOR = "#FFFFFF"
SHOP_SHEARCHBAR_LABEL_COLOR = "#797979"
SHOP_SHEARCHBAR_BORDER_COLOR = "#131313"
SHOP_SHEARCHBAR_COLOR_FOCUSED = "#484848"
SHOP_SHEARCHBAR_BORDER_COLOR_FOCUSED = "#4a9eff"
    # ------------------- Style des boutons ---------------
SHOP_BUTTON_BG_COLOR = "#2a2a3e"
SHOP_BUTTON_BORDER_COLOR = "#363656"
SHOP_BUTTON_BG_COLOR_HOVER = "#3a3a5e"
SHOP_BUTTON_BG_COLOR_CLICKED = "#2a2a47"
SHOP_BUTTON_IMG_BG_COLOR = "#222235"
SHOP_BUTTON_IMG_BORDER_COLOR = "#232335"
SHOP_BUTTON_IMG_ERROR_TXT_COLOR = "#ff8585"
SHOP_BUTTON_NAME_COLOR = "white"
SHOP_BUTTON_EFFECT_COLOR = "gray"
SHOP_BUTTON_BADGE_TXT_COLOR = "white"
SHOP_BUTTON_BADGE_BG_O2_COLOR = "#1a3a7c"
SHOP_BUTTON_BADGE_BORDER_O2_COLOR = "#006bb3"
SHOP_BUTTON_BADGE_BG_CO2_COLOR = "#1a4a2a"
SHOP_BUTTON_BADGE_BORDER_CO2_COLOR = "#2e8b39"
SHOP_BUTTON_BADGE_BG_STOCK_COLOR = "#7a6a00"
SHOP_BUTTON_BADGE_BORDER_STOCK_COLOR = "#bfa500"
    # ------------------- Style des cartes ----------------
SHOP_CARD_BG_COLOR = "#1e1e2e"
SHOP_CARD_TITLE_TEXT_COLOR = "#ffffff"
# à faire
SHOP_CARD_ITEM_NAME_COLOR = "#ffffff"
SHOP_CARD_ITEM_EFFECT_COLOR = "gray"
SHOP_CARD_ITEM_STOCK_COLOR = "#c6b544"
SHOP_CARD_ITEM_AMOUNT_SELECTED_TEXT_COLOR = "#cccccc" #
SHOP_CARD_ITEM_AMOUNT_SELECTED_BADGE_TEXT_COLOR = "white"
SHOP_CARD_ITEM_AMOUNT_SELECTED_BADGE_BG_COLOR = "#313540"
SHOP_CARD_ITEM_AMOUNT_SELECTED_BADGE_BORDER = (1,"#555555")
SHOP_CARD_ITEM_AMOUNT_SELECTOR_REMOVE_BG_COLOR = "#c0392b"
SHOP_CARD_ITEM_AMOUNT_SELECTOR_REMOVE_BG_HOVER_COLOR = "#e95b4b"
SHOP_CARD_ITEM_AMOUNT_SELECTOR_REMOVE_BORDER_COLOR = (1, "#a93226")
SHOP_CARD_ITEM_AMOUNT_SELECTOR_REMOVE_TEXT_COLOR = "white"
SHOP_CARD_ITEM_AMOUNT_SELECTOR_ADD_BG_COLOR = "#27ae60"
SHOP_CARD_ITEM_AMOUNT_SELECTOR_ADD_BG_HOVER_COLOR = "#35cc74"
SHOP_CARD_ITEM_AMOUNT_SELECTOR_ADD_BORDER_COLOR = (1, "#1e8449")
SHOP_CARD_ITEM_AMOUNT_SELECTOR_ADD_TEXT_COLOR = "white"


# —————————————————————————————————————————————————————————
# ———————————————————— Style Inventory ————————————————————
# —————————————————————————————————————————————————————————
    # ------------------- Style général -------------------

# —————————————————————————————————————————————————————————
# —————————————————————— Style Planet —————————————————————
# —————————————————————————————————————————————————————————
    # ------------------- Style général -------------------